---
title: "Get involved"


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#change block to flex to have side by side
# :::: {style="display: block;"}  
# 
# ::: {style="display: block;"}
```

## Join the mailing list

If you are the parent/caregiver of a minimally verbal / non-speaking person, a school, clinic, researcher or charity or anybody else with interest in my research, please [join the mailing list](https://qualtrics.ucl.ac.uk/jfe/form/SV_eKFsRuePNDwuk8C). 


## Join the research team

The lab is situated in the UCL Department of Clinical, Education and Health Psychology, in London's Bloomsbury neighbourhood, close to Euston and Russell Square stations. We are part of the broader Division of Psychology and Language Sciences (PALS), which includes a wide range of research departments such as UCL Institute of Cognitive Neuroscience, Experimental Psychology, Speech, Hearing and Phonetic Sciences (SHaPS) and Language and Cognition. Beyond PALS, UCL also has a Centre for Research in Autism and Education (CRAE) as part of IOE, UCL's Faculty of Education and Society.

### Placement opportunities for UCL Students

Undergraduate and MSc students at UCL may wish to participate in a research placement during their studies. Please get in touch with Jo, including a CV and a statement of your research interests.

### Visiting students and researchers

Jo is able to host students from other institutions for short research visits or placements. If you are interested please get in touch with your CV, details of the placement required (duration, timing) and a brief research proposal.

### Postdoctoral Fellowships

If you are interested in applying for a postdoctoral fellowship and are looking for a host institution and mentor, then please get in touch with some information about the target scheme and timeline, as well as a brief outline for a research proposal.

### PhD Studentships

Supervision of PhD students is possible subject to funding. Where fully-funded places are not already available, the student may have to compete for funding at UCL, or seek financial support from elsewhere.

If you are interested in completing a PhD in the lab, please email Jo with your CV, estimated start date and a brief research proposal.



## Contact details

Email: jo.saul.14@ucl.ac.uk

Bluesky: @josaul.bsky.social
